name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with gradle
      run: gradle build
    - name: Build the Docker image
      run: ./docker.build.sh
